version: "3.8"

services:
  shop-easier:
    build:
      context: .
      target: ui-dev
    ports:
      - "4050:4050"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - public
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    container_name: shop-easier-ui

networks:
  public:
    driver: bridge